name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Node.js and pnpm caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Enable pnpm via corepack
      - run: corepack enable

      # Step 3: Install dependencies using pnpm
      - run: pnpm install

      # Step 4: Run Nx tasks
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm nx affected -t lint test build
