name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Cache Node.js modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - run: npm ci --legacy-peer-deps
      # Adding an explicit `npm install` step
      - run: npm install

      # Step 4: Run Nx tasks
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build
